function k(b,a,c,d){b.v.Eb(b.lb,a,c,d)}function l(b,a,c,d){b.v.ca?k(b,a,c,d):b.v.xe()._OnMessageFromDOM({type:"event",component:b.lb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.v.C(b.lb,a,c)}function t(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Qb||(b.v.jd(b.Rd),b.Qb=!0)}window.Ka=class{constructor(b,a){this.v=b;this.lb=a;this.Qb=!1;this.Rd=()=>this.Na()}ad(){}Na(){}};
window.ff=class{constructor(){this.Yc=-1}j(){-1!==this.Yc&&(self.clearTimeout(this.Yc),this.Yc=-1)}};"use strict";function aa(b,a){n(b,"get-element",c=>{const d=v(b,c.elementId);return a(d,c)})}function v(b,a){b=b.Ob.get(a);if(!b)throw Error(`no element with id ${a}`);return b.ud}
window.ef=class extends self.Ka{constructor(b,a){super(b,a);this.Ob=new Map;this.Fc=!0;t(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=v(this,c);this.Fc&&d.parentElement.removeChild(d);this.Ob.delete(c)}],["set-visible",c=>{if(this.Fc){var d=this.Ob.get(c.elementId),e=d.ud;d.Ad?e.style.display=c.isVisible?"":"none":d.Me=!!c.isVisible}}],["update-position",c=>{if(this.Fc){var d=this.Ob.get(c.elementId),e=d.ud;e.style.left=c.left+"px";e.style.top=c.top+
"px";e.style.width=c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.Ad||(d.Ad=!0,d.Me&&(e.style.display=""))}}],["update-state",c=>{v(this,c.elementId);throw Error("required override");}],["focus",c=>this.Ac(c)],["set-css-style",c=>{const d=v(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{v(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{v(this,c.elementId).removeAttribute(c.name)}]]);
aa(this,c=>c)}Ac(b){var a=v(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent),ca=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let da=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Ve?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.Ze+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ea=!1,fa=!1;function ha(){if(!ea){try{new Worker("blob://",{get type(){fa=!0}})}catch(b){}ea=!0}return fa}let z=new Audio;
const ia={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}
function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let na=0;const oa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");oa.push(b)};const pa=new Set(["cordova","playable-ad","instant-games"]);let qa=!1;
window.ua=class b{constructor(a){this.ca=a.af;this.wa=null;this.ba="";this.$a=a.Ye;this.Bb={};this.Ta=this.ta=null;this.Nb=[];this.J=this.xa=null;this.Nc=!1;this.xd=0;this.qb=null;this.Za=-1;this.Qe=()=>this.Ee();this.Ya=[];this.u=a.Sd;this.Rb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ha()||(this.ca=!1);this.ca&&ca&&(this.ca=!1);if("playable-ad"===this.u||"instant-games"===this.u)this.ca=!1;if("cordova"===this.u&&this.ca)if(w){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Ub=this.qa=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.Ae(c));this.C("runtime","create-job-worker",()=>this.Be());"cordova"===this.u?document.addEventListener("deviceready",
()=>this.md(a)):this.md(a)}j(){this.sc();this.wa&&(this.wa=this.wa.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Ta&&(this.Ta.j(),this.Ta=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}me(){return ba&&"cordova"===this.u}oc(){const a=navigator.userAgent;return ba&&pa.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ke(){return w}fd(){return w&&pa.has(this.u)}async md(a){"macos-wkwebview"===this.u&&this.Dc({type:"ready"});if("playable-ad"===
this.u){this.qa=self.c3_base64files;this.Ub={};await this.te();for(let d=0,e=a.bb.length;d<e;++d){var c=a.bb[d];this.Ub.hasOwnProperty(c)?a.bb[d]={Ve:!0,Ze:this.Ub[c]}:this.qa.hasOwnProperty(c)&&(a.bb[d]=URL.createObjectURL(this.qa[c]))}a.hc=[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.jd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Xe?this.ba=a.Xe:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),
-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.cf&&(this.Bb=a.cf);c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.De(d));this.qb=new self.ne(this);await ra(this.qb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.ze(a,c.port2):await this.ye(a,c.port2)}uc(a){a=this.Bb.hasOwnProperty(a)?this.Bb[a]:a.endsWith("/workermain.js")&&this.Bb.hasOwnProperty("workermain.js")?this.Bb["workermain.js"]:"playable-ad"===this.u&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async jc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.Rb)return a=await this.Cb(d.Ue?a:this.$a+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}ld(a){var c=this.ba,d=location.href,e=this.oa(),f=this.ha(),g=window.devicePixelRatio,h=b.hb(),m=a.lf,p=window.cr_previewImageBlobs||this.qa,q=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.jf||
"";a=a.Sd;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.qb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.kf,jobScheduler:{inputPort:B.Mc,outputPort:B.Tc,maxNumWorkers:B.Ne},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$a+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.$a+"opus.wasm.wasm",isFileProtocol:this.Rb,isiOSCordova:this.me(),isiOSWebView:this.oc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ze(a,c){const d=this.uc(a.bf);"preview"===this.u?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const p=q=>{this.ta.removeEventListener("message",p);q.data&&"ok"===q.data.type?h():m()};this.ta.addEventListener("message",p);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.ta=await this.jc(d,this.ba,{type:"module",name:"Runtime",Ue:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.hc||[],g=a.bb;f=await Promise.all(f.map(h=>this.Oa(h)));g=await Promise.all(g.map(h=>this.Oa(h)));if("cordova"===this.u)for(let h=0,m=a.fc.length;h<m;++h){const p=
a.fc[h],q=p[0];if(q===a.Zc||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.Oa(q)}this.ta.postMessage(Object.assign(this.ld(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.fc,mainProjectScript:a.Zc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...sa(this.qb)]);this.Nb=F.map(h=>new h(this));this.kd();ta(this.xa);self.c3_callFunction=(h,m)=>{var p=this.xa;return p.v.hd(p.lb,"js-invoke-function",
{name:h,params:m})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.Eb("runtime","go-to-last-error-script"))}async ye(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Nb=F.map(g=>new g(this));this.kd();var d=a.bb.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.hc)){var e=[...a.hc].map(g=>g instanceof Blob?URL.createObjectURL(g):
g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Oa(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;e=a.Zc;const f=a.fc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Oa(h),await y(h),"preview"!==this.u||d[g]||this.od(g,"main script did not run to completion")}catch(m){this.od(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Oa(h),await y(h);"preview"===this.u&&"object"!==typeof self.df.gf?(this.Ib(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.ld(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:oa}),ta(this.xa),this.nd(),this.Ta=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ta,a))}od(a,c){this.Ib();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}nd(){this.Ib()}Ib(){const a=
window.Se;a&&(a.parentElement.removeChild(a),window.Se=null)}async Be(){const a=await va(this.qb);return{outputPort:a,transferables:[a]}}xe(){if(this.ca)throw Error("not available in worker mode");return this.Ta}Eb(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}hd(a,c,d,e,f){const g=na++,h=new Promise((m,p)=>{H.set(g,{resolve:m,reject:p})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ce(a);if("result"===c)this.Fe(a);else if("runtime-ready"===c)this.Ge();else if("alert-error"===c)this.Ib(),alert(a.message);else if("creating-runtime"===c)this.nd();else throw Error(`unknown message '${c}'`);}Ce(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Hb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Hb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Hb(f,!1,""+h)}):this.Hb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Hb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Fe(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}C(a,
c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static cb(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}kd(){for(const a of this.Nb)if("runtime"===a.lb){this.xa=a;return}throw Error("cannot find runtime DOM handler");}De(a){this.Eb("debugger","message",a)}Ge(){for(const a of this.Nb)a.ad()}static hb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
qa)}static Jb(a){qa=!!a}jd(a){this.Ya.push(a);this.Cc()}Ie(a){a=this.Ya.indexOf(a);if(-1===a)throw Error("invalid callback");this.Ya.splice(a,1);this.Ya.length||this.sc()}Cc(){-1===this.Za&&this.Ya.length&&(this.Za=requestAnimationFrame(this.Qe))}sc(){-1!==this.Za&&(cancelAnimationFrame(this.Za),this.Za=-1)}Ee(){this.Za=-1;for(const a of this.Ya)a();this.Cc()}Ca(a){this.xa.Ca(a)}Ma(a){this.xa.Ma(a)}Bc(){this.xa.Bc()}Gb(a){this.xa.Gb(a)}le(){return!!ia["audio/webm; codecs=opus"]}async Je(a){a=await this.hd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}pe(a){this.Nc=!0;this.xd=a}je(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}gd(a){return!this.je(a)}async Oa(a){return"cordova"===this.u&&(a.startsWith("file:")||this.Rb&&this.gd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Cb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ae(a){const c=a.filename;switch(a.as){case "text":return await this.ie(c);
case "buffer":return await this.Cb(c);default:throw Error("unsupported type");}}dd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ie(a){a=await this.dd(a);return await ja(a)}tc(){if(C.length&&!(8<=E)){E++;var a=C.shift();this.ue(a.filename,a.$e,a.Te)}}Cb(a){return new Promise((c,d)=>{C.push({filename:a,$e:e=>{E--;this.tc();c(e)},Te:e=>{E--;this.tc();d(e)}});this.tc()})}async ue(a,c,d){try{const e=
await this.dd(a),f=await ka(e);c(f)}catch(e){d(e)}}Dc(a){if("windows-webview2"===this.u)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.u)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async te(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.se(c,d));await Promise.all(a)}async se(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.Ub[a]=c.str;else{let d=
await this.we(c);d||(d=this.ve(c));this.qa[a]=d}}async we(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}ve(a){a=this.He(a);return this.re(a.data,a.We)}He(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,
c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{We:a,data:d}}re(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const I=self.ua;
function wa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const xa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ya={dispatchUserScriptEvent:!0},za={dispatchRuntimeEvent:!0};
function Aa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ba(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await Ba(b)}finally{URL.revokeObjectURL(b)}}
function Ca(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Da(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Ca(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Ea(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Fa=new Set(["input","textarea","datalist","select"]),Ga=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ga.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ha(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Da(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ia=!1;document.addEventListener("pause",()=>Ia=!0);document.addEventListener("resume",()=>Ia=!1);function ta(b){b.wd=!0;b.Qc=b.v.oa();b.rb=b.v.ha()}async function Ja(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function La(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ma(b){return await self.C3_GetSvgImageSize(b.blob)}function Na(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Oa(b){self.setTimeout(()=>{b.vd=!0},1E3);"cordova"===b.v.u?(document.addEventListener("pause",()=>Pa(b,!0)),document.addEventListener("resume",()=>Pa(b,!1))):document.addEventListener("visibilitychange",()=>Pa(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ia)}}
function Qa(b){b.qd||(b.qd=!0,window.addEventListener("deviceorientation",a=>{b.$||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Ra(b){b.pd||(b.pd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Sa(b){await Aa(b.url)}
function Ta(b,a){b.yd=a.message;-1===b.Ic&&(b.Ic=setTimeout(()=>{b.Ic=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.yd)},250))}function M(b){if(!b.$){var a=I.hb();a&&"any"!==b.Wc&&Ua(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ha()})}}function Va(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:I.hb(),innerWidth:b.oa(),innerHeight:b.ha()})}
function Pa(b,a){a?b.v.sc():b.v.Cc();k(b,"visibilitychange",{hidden:a})}function Wa(b,a,c){"Backspace"===c.key&&L(c);if(!b.$){var d=xa.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J)}}
function Xa(b,a,c,d){b.$||wa(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Ya(b){window!==window.top&&window.focus();Za(b.target)&&document.activeElement&&!Za(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.wb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Xa(b,d,c,ya),b.wb=c.buttons)}}
function $a(b,a,c){if(!b.$&&!wa(c)){var d=b.wb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},J);b.wb=c.buttons;Xa(b,c.type,c,ya)}}
function O(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
J)}}function ab(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function bb(b,a,c,d){const e=b.oa(),f=b.ha();b.ab=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.hb()}):10>d&&cb(b,e,f,d+1)}
function cb(b,a,c,d){-1!==b.ab&&clearTimeout(b.ab);b.ab=setTimeout(()=>bb(b,a,c,d),48)}
function Ua(b){b=b.Wc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Za(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.cb(class extends self.Ka{constructor(b){super(b,"runtime");this.Ed=!0;this.wd=!1;this.ab=-1;this.Wc="any";this.pd=this.qd=!1;this.cc=document.createElement("div");this.cc.className="c3-screen-reader-text";this.cc.setAttribute("aria-live","polite");document.body.appendChild(this.cc);this.Fa=null;this.$=!1;this.yd="";this.Ic=-1;this.vd=!1;this.Qc=b.oa();this.rb=b.ha();this.da=this.Ab=0;b.C("canvas","update-size",d=>{var e=this.v;e.Nc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Ed&&(e.style.display="",this.Ed=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ja(d));b.C("runtime","raster-svg-image",d=>La(d));b.C("runtime","get-svg-image-size",
d=>Ma(d));b.C("runtime","set-target-orientation",d=>{this.Wc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Na(d));b.C("runtime","go-to-script",d=>Na(d));b.C("runtime","before-start-ticking",()=>Oa(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Fa||(this.Fa=document.createElement("div"),this.Fa.id="inspectOutline",document.body.appendChild(this.Fa));var e=this.Fa;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Fa&&(this.Fa.style.display="none")});b.C("runtime","enable-device-orientation",()=>Qa(this));b.C("runtime","enable-device-motion",()=>Ra(this));b.C("runtime","add-stylesheet",d=>Sa(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>this.xc(d));b.C("runtime",
"screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.cc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.J.style.display="";this.v.pe(d.duration)});b.C("runtime","export-to-video-progress",d=>Ta(this,d));b.C("runtime","exported-to-video",d=>{window.Re({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Re({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ea(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);c.addEventListener("selectstart",L);c.addEventListener("gesturehold",
L);window.addEventListener("touchstart",L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),c.addEventListener("pointerdown",L)):c.addEventListener("touchstart",L);this.wb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ha,{passive:!1});window.addEventListener("wheel",Ha,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.wd){var d=this.oa();var e=this.ha();if(this.v.fd()){if(this.vd){if(this.Qc===
d&&e<this.rb){this.Ab=this.rb-e;ab(this,this.rb,this.Ab);d=void 0;break a}0<this.Ab&&(this.Ab=0,ab(this,e,this.Ab))}this.Qc=d;this.rb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.hb()});this.v.oc()&&(-1!==this.ab&&clearTimeout(this.ab),bb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",()=>M(this));window.addEventListener("mozfullscreenchange",()=>
M(this));window.addEventListener("fullscreenerror",d=>Va(this,d));window.addEventListener("webkitfullscreenerror",d=>Va(this,d));window.addEventListener("mozfullscreenerror",d=>Va(this,d));if(b.oc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ea(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(I.Jb(!0),M(this)):"exited-fullscreen"===d?(I.Jb(!1),M(this)):console.warn("Unknown wrapper message: ",d)};this.Ua=new Set;this.Wb=new WeakSet;this.va=!1}ad(){window.addEventListener("focus",()=>{k(this,"window-focus",null,za)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}k(this,"window-blur",{parentHasFocus:a},za);this.wb=0});window.addEventListener("focusin",a=>{a=a.target;(Fa.has(a.tagName.toLowerCase())||Ea(a))&&k(this,"keyboard-blur",null,za)});window.addEventListener("keydown",a=>Wa(this,"keydown",a));window.addEventListener("keyup",a=>Wa(this,"keyup",a));window.addEventListener("dblclick",a=>Xa(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.$||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,
deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Ya(a);N(this,"pointerdown",a)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Ya(a);$a(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>$a(this,"pointermove",a)),window.addEventListener("mouseup",a=>$a(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Ya(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=
()=>this.Bc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.ke()&&!this.v.fd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{ab(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}))}oa(){return this.v.oa()}ha(){return this.v.ha()}Bc(){var b=
[...this.Ua];this.Ua.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.Wb.has(a)||this.Ua.add(a)})}Ca(b){if("function"!==typeof b.play)throw Error("missing play function");this.Wb.delete(b);let a;try{a=b.play()}catch(c){this.Ua.add(b);return}a&&a.catch(()=>{this.Wb.has(b)||this.Ua.add(b)})}Ma(b){this.Ua.delete(b);this.Wb.add(b)}Gb(b){this.va=!!b}xc(b){alert(b.message)}});"use strict";
async function ra(b){if(b.Ke)throw Error("already initialised");b.Ke=!0;var a=b.ya.uc(("playable-ad"===b.ya.u?b.ya.$a:"")+"dispatchworker.js");b.Hc=await b.ya.jc(a,b.kb,{name:"DispatchWorker"});a=new MessageChannel;b.Mc=a.port1;b.Hc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Tc=await va(b)}function sa(b){return[b.Mc,b.Tc]}
async function va(b){const a=b.Fd.length;var c=b.ya.uc(("playable-ad"===b.ya.u?b.ya.$a:"")+"jobworker.js");c=await b.ya.jc(c,b.kb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Hc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Fd.push(c);return e.port1}
self.ne=class{constructor(b){this.ya=b;this.kb=b.ba;this.kb="preview"===b.u?this.kb+"workers/":this.kb+b.$a;this.Ne=Math.min(navigator.hardwareConcurrency||2,16);this.Hc=null;this.Fd=[];this.Tc=this.Mc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ua({af:!1,bf:"workermain.js",bb:["scripts/c3runtime.js"],fc:[],Zc:"",Ye:"scripts/",hc:[],Sd:"html5"}));"use strict";const db=180/Math.PI;
async function fb(b,a){if(a.isiOSCordova||a.isSafari)b.Zb=!0;b.Xc=a.timeScaleMode;b.Kd=["equalpower","HRTF","soundfield"][a.panningModel];b.td=["linear","inverse","exponential"][a.distanceModel];b.Ld=a.refDistance;b.Jd=a.maxDistance;b.Nd=a.rolloffFactor;if(b.v.Nc)b.Zb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.xd)});else{var c={latencyHint:a.latencyHint};b.Qd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");gb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&gb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Qa=b.g.createGain();b.Qa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function hb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Gd=g.slice(0);ib(b,g);try{b.R=await jb(b,c,d,e,g,f);if(q){Q(b.R,!0);var r=b.R,B=q.innerAngle,la=q.outerAngle,ma=q.outerGain;if(r.pb){kb(r,q.x,q.y,q.z,q.angle);var D=self.eb.qe;r.ra[0]!==D(B)&&
(r.ra[0]=D(B),r.F.coneInnerAngle=D(B));r.ra[1]!==D(la)&&(r.ra[1]=D(la),r.F.coneOuterAngle=D(la));r.ra[2]!==ma&&(r.ra[2]=ma,r.F.coneOuterGain=ma)}q.hasOwnProperty("uid")&&(b.R.pa=q.uid)}else"number"===typeof A&&0!==A?(R(b.R,!0),lb(b.R,A)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,m,p,x)}catch(zb){console.error("[Construct] Audio: error starting playback: ",zb);return}finally{c=g.join(" ");d=b.yb.get(c);if(!d)throw Error("expected pending tag");d.$c--;0===d.$c&&(d.resolve(),b.yb.delete(c))}u(b)}
async function mb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await nb(b,c);for(const h of S(b,c))if(!h.Sa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.s.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ja=d;h.Ra=g;h.Pd=a}T(b)}async function ob(b,a){const c=a.tags;a=a.rate;await nb(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Da())}async function pb(b,a){const c=a.tags;a=a.pos;await nb(b,c);for(const d of S(b,c))d.pc(a)}
async function qb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await jb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function rb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function sb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct] Audio: error loading convolution: ",m);return}for(const m of d){if("filter"===c)d=new self.Yd(b,...e);else if("delay"===c)d=new self.Wd(b,...e);else if("convolution"===c){var g=d=new self.Vd(b,f.ia,...e),h=a.bufferType;g.rd=a.bufferOriginalUrl;g.sd=h}else if("flanger"===c)d=new self.Zd(b,...e);else if("phaser"===
c)d=new self.ae(b,...e);else if("gain"===c)d=new self.$d(b,...e);else if("stereopan"===c)d=new self.ce(b,...e);else if("tremolo"===c)d=new self.de(b,...e);else if("ringmod"===c)d=new self.be(b,...e);else if("distortion"===c)d=new self.Xd(b,...e);else if("compressor"===c)d=new self.Ud(b,...e);else if("analyser"===c)d=new self.Td(b,...e);else throw Error("invalid effect type");g=b;h=m;h=h.toLowerCase();let p=g.ka.get(h);p||(p=[],g.ka.set(h,p));d.Dd=p.length;d.Vc=h;p.push(d);tb(g,h)}ub(b)}
async function vb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Aa()&&1===c||!e.Aa()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ka.values())for(const g of f)g.j();b.ka.clear();b.dc=a.timeScale;b.Jc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.va=a.isSilent;b.v.Gb(b.va);b.Vb=a.masterVolume;b.Qa.gain.value=
b.Vb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>sb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>wb(b,f,c)));T(b)}
async function xb(b,a){try{const c=b.g.suspend(a.time);b.Cd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Eb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>yb(d)),b.Cd=!0);await c}catch(c){yb(c)}}
function gb(b){b.Pb||(b.Lc=!1,window.addEventListener("pointerup",b.za,!0),window.addEventListener("touchend",b.za,!0),window.addEventListener("click",b.za,!0),window.addEventListener("keydown",b.za,!0),b.Pb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ja)if(g.gb()===c)return await Ab(g),g;if(f)return null;if(e&&(b.Zb||b.Bd)){f=0;for(let h=0,m=b.ja.length;h<m;++h)g=b.ja[h],b.ja[f]=g,g.Aa()?g.j():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.Qd;e&&f&&(b.Bd=!0);c=!e||b.Zb||f?new self.ge(b,a,c,d,e,f):new self.ee(b,a,c,d,e);b.ja.push(c);await Ab(c);b.Id.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.Id.add(a));return c}
function Bb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Cb(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.na()}function tb(b,a){a=a.toLowerCase();let c=b.na();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.na()):e.U(d[f+1].N())}}for(const f of Db(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ga&&b.Rc===a&&(b.Ga.disconnect(),b.Ga.connect(c))}
function*Db(b,a){if(a)for(const c of b.H)Bb(0<c.ma.length?c.ma[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Eb(b,a,c){return c?b.v.Je(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Fb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.ma;var c=a;for(const e of c){c=!1;for(const f of b)if(Bb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function jb(b,a,c,d,e,f){for(const g of b.H)if(g.gb()===c&&(g.ic()||f))return g.ma=e,g;a=await P(b,a,c,d,f);e="html5"===a.Ec?new self.fe(a.s,a,e):new self.he(a.s,a,e);b.H.push(e);return e}
function ib(b,a){a=a.join(" ");let c=b.yb.get(a);if(!c){let d=null;c={$c:0,promise:new Promise(e=>d=e),resolve:d};b.yb.set(a,c)}c.$c++}function nb(b,a){return(b=b.yb.get((0===a.length?b.Gd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Pa.size)u(b);else for(const a of b.H)if(!a.I&&!a.O()){u(b);break}}function Gb(b,a,c,d){k(b,"trigger",{type:a,tags:c,aiid:d})}function ub(b){b.Oc||(b.Oc=!0,Promise.resolve().then(()=>Hb(b)))}
function Hb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.fb());k(b,"fxstate",{fxstate:a});b.Oc=!1}
async function wb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await jb(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Wa[0]=f[0],b.Wa[1]=f[1],b.Wa[2]=f[2],f=d.orient,b.Va[0]=f[0],b.Va[1]=f[1],b.Va[2]=f[2],e.setPosition(...b.Wa),e.setOrientation(...b.Va),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),lb(b,d));c.Play(m,p,q,0);a.isPlaying||c.ib();c.wc(a)}}}function yb(b){console.error("[Audio] Offline rendering error: ",b)}
self.eb=class extends self.Ka{constructor(b){super(b,"audio");this.Qa=this.g=null;this.Pb=this.Lc=!1;this.za=()=>{if(!this.Lc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Pb&&(this.Lc=!0,window.removeEventListener("pointerup",this.za,!0),window.removeEventListener("touchend",this.za,!0),window.removeEventListener("click",this.za,!0),window.removeEventListener("keydown",
this.za,!0),this.Pb=!1)}};this.ja=[];this.H=[];this.R=null;this.Gd=[];this.Id=new Set;this.Hd=-1;this.yb=new Map;this.Vb=1;this.va=!1;this.Xc=0;this.dc=1;this.Jc=0;this.Kd="HRTF";this.td="inverse";this.Ld=600;this.Jd=1E4;this.Nd=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Bd=this.Zb=!1;this.Qd=this.v.le();this.ka=new Map;this.Pa=new Set;this.Cd=this.Oc=!1;this.Rc="";this.Ga=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ga&&this.Ga.disconnect();this.Rc=c.toLowerCase();this.Ga=this.g.createMediaStreamSource(a);
this.Ga.connect(Cb(this,this.Rc))};this.Mb=null;self.C3Audio_GetOutputStream=()=>{this.Mb||(this.Mb=this.g.createMediaStreamDestination(),this.Qa.connect(this.Mb));return this.Mb.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>fb(this,a)],["play",a=>hb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ba()}],["stop-all",()=>{for(const a of this.H)a.Ba()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.ib():d.Fb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>mb(this,a)],["set-master-volume",a=>{this.Vb=a.vol;this.Qa.gain.value=this.Vb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Ib(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.v.Gb(this.va);for(const c of this.H)c.Kb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.qc(a)}],["set-playback-rate",a=>ob(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),lb(d,a)}],["seek",a=>pb(this,a)],["preload",a=>qb(this,a)],["unload",a=>rb(this,a)],["unload-all",()=>{for(const a of this.ja)a.j();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.rc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>sb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);ub(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ka.delete(a);tb(this,a)}}],["tick",a=>{this.dc=a.timeScale;this.Jc=a.gameTime;this.Hd=a.tickCount;if(0!==this.Xc)for(var c of this.H)c.Da();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.pa===a&&kb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>vb(this,a)],["offline-render-audio",a=>xb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}W(){return this.g}na(){return this.Qa}Db(){return this.va}Ca(b){this.v.Ca(b)}Ma(b){this.v.Ma(b)}Na(){for(var b of this.Pa)b.Na();
b=this.g.currentTime;for(var a of this.H)a.Na(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.fb());k(this,"state",{tickCount:this.Hd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Pa].map(c=>({tag:c.Vc,index:c.Dd,peak:c.Xa,rms:c.Md,binCount:c.l.frequencyBinCount,freqBins:c.zd}))});0===a.length&&0===this.Pa.size&&this.Qb&&(this.v.Ie(this.Rd),this.Qb=!1)}static qe(b){return b*db}static ed(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static oe(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.ua.cb(self.eb);"use strict";function Ab(b){b.Tb||(b.Tb=b.vc());return b.Tb}self.bd=class{constructor(b,a,c,d,e){this.s=b;this.Pe=a;this.Ia=c;this.T=d;this.Le=e;this.Ec="";this.Tb=null}j(){this.Tb=this.s=null}vc(){}W(){return this.s.W()}lc(){return this.Pe}gb(){return this.Ia}kc(){return this.T}Aa(){return this.Le}ga(){}};"use strict";
self.ee=class extends self.bd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ec="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.sb=this.tb=null;this.M.addEventListener("canplaythrough",()=>!0);this.xb=this.W().createGain();this.vb=null;this.M.addEventListener("canplay",()=>{this.tb&&(this.tb(),this.sb=this.tb=null);!this.vb&&this.M&&(this.vb=this.W().createMediaElementSource(this.M),this.vb.connect(this.xb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ia}' error: `,f);this.sb&&(this.sb(f),this.sb=this.tb=null)})}j(){Fb(this.s,this);this.xb.disconnect();this.xb=null;this.vb.disconnect();this.vb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}vc(){return new Promise((b,a)=>{this.tb=b;this.sb=a;this.M.src=this.Ia})}V(){return this.M}ga(){return this.M.duration}};"use strict";
async function Jb(b){if(b.Ea)return b.Ea;var a=b.s.v;if("cordova"===a.u&&a.gd(b.Ia)&&a.Rb)b.Ea=await a.Cb(b.Ia);else{a=await fetch(b.Ia);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ea=await a.arrayBuffer()}}async function Kb(b){if(b.ia)return b.ia;b.ia=await Eb(b.s,b.Ea,b.Oe);b.Ea=null}
self.ge=class extends self.bd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ec="webaudio";this.ia=this.Ea=null;this.Oe=!!f}j(){Fb(this.s,this);this.ia=this.Ea=null;super.j()}async vc(){try{await Jb(this),await Kb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ia}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Lb=0;
function Q(b,a){a=!!a;b.pb!==a&&(b.pb=a,b.pb?(R(b,!1),b.F||(b.F=b.W().createPanner(),b.F.panningModel=b.s.Kd,b.F.distanceModel=b.s.td,b.F.refDistance=b.s.Ld,b.F.maxDistance=b.s.Jd,b.F.rolloffFactor=b.s.Nd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function R(b,a){a=!!a;b.Sb!==a&&(b.Sb=a,b.Sb?(Q(b,!1),b.fa=b.W().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.na())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.na())))}function lb(b,a){b.Sb&&b.Uc!==a&&(b.fa.pan.value=a,b.Uc=a)}function U(b,a){b.Ja=a;b.G.gain.cancelScheduledValues(0);b.Ra=-1;b.G.gain.value=b.mc()}function Ib(b,a){a=!!a;b.Sa!==a&&(b.Sa=a,b.Kb())}
function kb(b,a,c,d,e){if(b.pb){var f=b.Wa,g=b.Va,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Pc?b.s.Jc:performance.now()/1E3}
self.cd=class{constructor(b,a,c){this.s=b;this.P=a;this.ma=c;this.Lb=Lb++;this.G=this.W().createGain();this.G.connect(this.na());this.F=null;this.pb=!1;this.Wa=[0,0,0];this.Va=[0,0,0];this.ra=[0,0,0];this.fa=null;this.Sb=!1;this.Uc=0;this.I=!0;this.Y=this.sa=this.K=!1;this.Ja=1;this.Sa=!1;this.la=1;b=this.s.Xc;this.Pc=1===b&&!this.Aa()||2===b;this.Ra=this.pa=-1;this.Pd=!1}j(){this.P=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}W(){return this.s.W()}na(){return Cb(this.s,0<this.ma.length?this.ma[0]:"")}lc(){return this.P.lc()}gb(){return this.P.gb()}kc(){return this.P.kc()}Aa(){return this.P.Aa()}O(){}ic(){}IsPlaying(){return!this.I&&!this.K&&!this.O()}La(){}ga(){return this.P.ga()}Play(){}Ba(){}ib(){}Fb(){}Na(b){-1!==this.Ra&&b>=this.Ra&&(this.Ra=-1,this.Pd&&this.Ba(),Gb(this.s,"fade-ended",this.ma,this.Lb))}mc(){const b=this.Ja;return isFinite(b)?b:0}Db(){return this.s.Db()}Kb(){}qc(){}Da(){}pc(){}rc(){}nc(){}fb(){var b=
this.Lb,a=this.ma,c=this.ga(),d=-1===this.Ra?this.Ja:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Wa,orient:this.Va,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.La(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.lc(),bufferUrl:"",bufferType:this.kc(),isMusic:this.Aa(),isLooping:this.Y,isMuted:this.Sa,resumePosition:this.nc(),pan:f,stereoPan:this.fa?
this.Uc:null}}wc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Da());Ib(this,b.isMuted)}};"use strict";
self.fe=class extends self.cd{constructor(b,a,c){super(b,a,c);this.P.xb.connect(this.G);this.P.onended=()=>this.yc()}j(){this.Ba();this.P.xb.disconnect();super.j()}V(){return this.P.V()}yc(){this.I=!0;this.pa=-1;Gb(this.s,"ended",this.ma,this.Lb)}O(){return this.V().ended}ic(){return this.I?!0:this.O()}La(){let b=this.V().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.V();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.gb()}' to position '${c}': `,e)}this.s.Ca(d);this.K=this.I=!1;this.Y=b;this.la=1}Ba(){const b=this.V();b.paused||b.pause();this.s.Ma(b);this.I=!0;this.K=!1;this.pa=-1}ib(){if(!(this.K||this.I||this.O())){var b=this.V();b.paused||b.pause();this.s.Ma(b);this.K=!0}}Fb(){!this.K||this.I||this.O()||(this.s.Ca(this.V()),this.K=!1)}Kb(){this.V().muted=this.Sa||this.Db()}qc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.V().loop=b)}Da(){let b=this.la;this.Pc&&(b*=this.s.dc);try{this.V().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}pc(b){if(!this.I&&!this.O())try{this.V().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}nc(){return this.La()}rc(b){b?this.IsPlaying()?(this.V().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.s.Ca(this.V()),this.sa=!1)}};"use strict";
function W(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.jb=null}
self.he=class extends self.cd{constructor(b,a,c){super(b,a,c);this.o=null;this.Xb=d=>this.yc(d);this.Kc=!0;this.jb=null;this.S=this.Yb=this.$b=0;this.Sc=1}j(){this.Ba();W(this);this.Xb=null;super.j()}yc(b){this.K||this.sa||b.target!==this.jb||(this.I=this.Kc=!0,this.pa=-1,W(this),Gb(this.s,"ended",this.ma,this.Lb))}O(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Kc}ic(){return!this.o||this.I?!0:this.O()}La(){let b;b=this.K?this.S:this.Yb+(V(this)-this.$b)*this.la;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.Sc=1;U(this,a);W(this);this.o=this.W().createBufferSource();this.o.buffer=this.P.ia;this.o.connect(this.G);this.jb=this.o;this.o.onended=this.Xb;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Kc=!1;this.Y=b;this.la=1;this.$b=V(this);this.Yb=c}Ba(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.pa=-1}ib(){this.K||this.I||this.O()||(this.S=this.La(),this.Y&&(this.S%=this.ga()),this.K=!0,this.o.stop(0))}Fb(){!this.K||this.I||this.O()||(W(this),this.o=
this.W().createBufferSource(),this.o.buffer=this.P.ia,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.Xb,this.o.loop=this.Y,U(this,this.Ja),this.Da(),this.o.start(0,this.S),this.$b=V(this),this.Yb=this.S,this.K=!1)}mc(){return super.mc()*this.Sc}Kb(){this.Sc=this.Sa||this.Db()?0:1;U(this,this.Ja)}qc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Da(){let b=this.la;this.Pc&&(b*=this.s.dc);this.o&&(this.o.playbackRate.value=b)}pc(b){this.I||this.O()||(this.K?this.S=b:(this.ib(),this.S=
b,this.Fb()))}nc(){return this.S}rc(b){b?this.IsPlaying()?(this.sa=!0,this.S=this.La(),this.Y&&(this.S%=this.ga()),this.o.stop(0)):this.sa=!1:this.sa&&(W(this),this.o=this.W().createBufferSource(),this.o.buffer=this.P.ia,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.Xb,this.o.loop=this.Y,U(this,this.Ja),this.Da(),this.o.start(0,this.S),this.$b=V(this),this.Yb=this.S,this.sa=!1)}wc(b){super.wc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.W();this.Dd=-1;this.T=this.Vc="";this.m=null}j(){this.g=null}N(){}U(){}fb(){return{type:this.T,tag:this.Vc,params:this.m}}}
self.Yd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.Wd=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.ub=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.nb=X(this);this.nb.gain.value=c;this.A.connect(this.ub);this.A.connect(this.h);this.ub.connect(this.i);this.ub.connect(this.X);this.X.connect(this.nb);this.nb.connect(this.ub)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.ub.disconnect();
this.X.disconnect();this.nb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.eb.ed;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.nb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.Vd=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.sd=this.rd="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.mb=this.g.createConvolver();this.mb.normalize=c;this.mb.buffer=a;this.A.connect(this.mb);this.A.connect(this.h);this.mb.connect(this.i)}j(){this.A.disconnect();this.mb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}fb(){const b=super.fb();b.bufferOriginalUrl=this.rd;b.bufferUrl="";b.bufferType=this.sd;return b}};
self.Zd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.ob=X(this);this.ob.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.ob);this.ob.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.ob.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.ob.gain,a/100,c,d)}}};
self.ae=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.$d=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.eb.ed;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.ce=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.de=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.be=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.zb=X(this);this.zb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.zb.gain);this.B.start(0);this.A.connect(this.zb);this.A.connect(this.h);this.zb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.zb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.Xd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.A=X(this);this.bc=X(this);this.ac=X(this);b=d;.01>b&&(b=.01);this.bc.gain.value=b;this.ac.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.ec=this.g.createWaveShaper();this.Gc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Gc[32768+e]=f,this.Gc[32768-
e-1]=-f;this.ec.curve=this.Gc;this.A.connect(this.bc);this.A.connect(this.h);this.bc.connect(this.ec);this.ec.connect(this.ac);this.ac.connect(this.i)}j(){this.A.disconnect();this.bc.disconnect();this.ec.disconnect();this.ac.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Ud=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Td=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.zd=new Float32Array(this.l.frequencyBinCount);this.Od=new Uint8Array(a);this.Md=this.Xa=0;b=this.s;b.Pa.add(this);T(b)}j(){this.s.Pa.delete(this);this.l.disconnect();super.j()}Na(){this.l.getFloatFrequencyData(this.zd);this.l.getByteTimeDomainData(this.Od);const b=this.l.fftSize;let a=this.Xa=0;for(var c=0;c<b;++c){let d=(this.Od[c]-
128)/128;0>d&&(d=-d);this.Xa<d&&(this.Xa=d);a+=d*d}c=self.eb.oe;this.Xa=c(this.Xa);this.Md=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";async function Mb(b,a){a=a.type;let c=!0;0===a?c=await Nb():1===a&&(c=await Ob());k(b,"permission-result",{type:a,result:c})}
async function Nb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Ob(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ua.cb(class extends self.Ka{constructor(b){super(b,"touch");n(this,"request-permission",a=>Mb(this,a))}});"use strict";function Pb(){}
function Qb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Rb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.ua.cb(class extends self.Ka{constructor(b){super(b,"browser");this.u="";t(this,[["get-initial-state",a=>this.zc(a)],["ready-for-sw-messages",()=>Qb(this)],["alert",a=>this.xc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ac(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Rb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.hf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.u||"macos-wkwebview"===this.u)self.ua.Jb(!0),
this.v.Dc({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof
Promise&&d.catch(Pb)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.u||"macos-wkwebview"===this.u)self.ua.Jb(!1),this.v.Dc({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Pb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",
a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:
{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}zc(b){this.u=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,
referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}xc(b){alert(b.message)}Ac(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";
function Sb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}function Tb(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function Ub(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function Vb(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}
async function Wb(b){if(!b.Ha)try{b.Ha=await navigator.wakeLock.request("screen"),b.Ha.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Ha=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
async function Xb(b){const a=await Yb();k(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function Yb(){var b=self.AndroidNotch;if(b)try{return await Promise.all([Sb(b),Tb(b),Ub(b),Vb(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.ua.cb(class extends self.Ka{constructor(b){super(b,"platform-info");t(this,[["get-initial-state",()=>this.zc()],["request-wake-lock",()=>Wb(this)],["release-wake-lock",()=>{this.Ha&&(this.Ha.release(),this.Ha=null)}]]);window.addEventListener("resize",()=>Xb(this));this.Ha=null}async zc(){const b=await Yb();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==
typeof nw}}});
